// Auto-generated from NIST SP 800-171A assessment procedures
export type Objective = { letter: string; text: string }
export const ASSESSMENT_OBJECTIVES: Record<string, Objective[]> = {
  'AC.L2-3.1.1': [
    { letter: 'a', text: 'authorized users are identified.' },
    { letter: 'b', text: 'processes acting on behalf of authorized users are identified.' },
    { letter: 'c', text: 'devices (including other systems) authorized to connect to the system are identified.' },
    { letter: 'd', text: 'system access is limited to authorized users.' },
    { letter: 'e', text: 'system access is limited to processes acting on behalf of authorized users.' },
    { letter: 'f', text: 'system access is limited to authorized devices (including other systems).' },
  ],
  'AC.L2-3.1.10': [
    { letter: 'a', text: 'the period of inactivity after which the system initiates a session lock is defined.' },
    { letter: 'b', text: 'access to the system and viewing of data is prevented by initiating a session lock after the defined period of inactivity.' },
    { letter: 'c', text: 'previously visible information is concealed via a pattern-hiding display after the defined period of inactivity.' },
  ],
  'AC.L2-3.1.11': [
    { letter: 'a', text: 'conditions requiring a user session to terminate are defined.' },
    { letter: 'b', text: 'a user session is automatically terminated after any of the defined conditions occur.' },
  ],
  'AC.L2-3.1.12': [
    { letter: 'a', text: 'remote access sessions are permitted.' },
    { letter: 'b', text: 'the types of permitted remote access are identified.' },
    { letter: 'c', text: 'remote access sessions are controlled.' },
    { letter: 'd', text: 'remote access sessions are monitored.' },
  ],
  'AC.L2-3.1.13': [
    { letter: 'a', text: 'cryptographic mechanisms to protect the confidentiality of remote access sessions are identified.' },
    { letter: 'b', text: 'cryptographic mechanisms to protect the confidentiality of remote access sessions are implemented.' },
  ],
  'AC.L2-3.1.14': [
    { letter: 'a', text: 'managed access control points are identified and implemented.' },
    { letter: 'b', text: 'remote access is routed through managed network access control points.' },
  ],
  'AC.L2-3.1.15': [
    { letter: 'a', text: 'privileged commands authorized for remote execution are identified.' },
    { letter: 'b', text: 'security-relevant information authorized to be accessed remotely is identified.' },
    { letter: 'c', text: 'the execution of the identified privileged commands via remote access is authorized.' },
    { letter: 'd', text: 'access to the identified security-relevant information via remote access is authorized.' },
  ],
  'AC.L2-3.1.16': [
    { letter: 'a', text: 'wireless access points are identified.' },
    { letter: 'b', text: 'wireless access is authorized prior to allowing such connections.' },
  ],
  'AC.L2-3.1.17': [
    { letter: 'a', text: 'wireless access to the system is protected using encryption.' },
    { letter: 'b', text: 'wireless access to the system is protected using authentication.' },
  ],
  'AC.L2-3.1.18': [
    { letter: 'a', text: 'mobile devices that process, store, or transmit CUI are identified.' },
    { letter: 'b', text: 'the connection of mobile devices is authorized.' },
    { letter: 'c', text: 'mobile device connections are monitored and logged.' },
  ],
  'AC.L2-3.1.19': [
    { letter: 'a', text: 'mobile devices and mobile computing platforms that process, store, or transmit CUI are identified.' },
    { letter: 'b', text: 'encryption is employed to protect CUI on identified mobile devices and mobile computing platforms.' },
  ],
  'AC.L2-3.1.2': [
    { letter: 'a', text: 'the types of transactions and functions that authorized users are permitted to execute are defined' },
    { letter: 'b', text: 'system access is limited to the defined types of transactions and functions for authorized users.' },
  ],
  'AC.L2-3.1.20': [
    { letter: 'a', text: 'connections to external systems are identified.' },
    { letter: 'b', text: 'use of external systems is identified.' },
    { letter: 'c', text: 'connections to external systems are verified.' },
    { letter: 'd', text: 'use of external systems is verified.' },
    { letter: 'e', text: 'connections to external systems are controlled/limited.' },
    { letter: 'f', text: 'use of external systems is controlled/limited.' },
  ],
  'AC.L2-3.1.21': [
    { letter: 'a', text: 'use of organizational portable storage devices containing CUI on external systems is identified and documented.' },
    { letter: 'b', text: 'limits on the use of organizational portable storage devices containing CUI on external systems are defined.' },
    { letter: 'c', text: 'use of organizational portable storage devices containing CUI on external systems is limited as defined.' },
  ],
  'AC.L2-3.1.22': [
    { letter: 'a', text: 'individuals authorized to post or process information on publicly accessible systems are identified.' },
    { letter: 'b', text: 'procedures to ensure CUI is not posted or processed on publicly accessible systems are identified.' },
    { letter: 'c', text: 'a review process in in place prior to posting of any content to publicly accessible systems.' },
    { letter: 'd', text: 'content on publicly accessible information systems is reviewed to ensure that it does not include CUI.' },
    { letter: 'e', text: 'mechanisms are in place to remove and address improper posting of CUI.' },
  ],
  'AC.L2-3.1.3': [
    { letter: 'a', text: 'information flow control policies are defined.' },
    { letter: 'b', text: 'methods and enforcement mechanisms for controlling the flow of CUI are defined.' },
    { letter: 'c', text: 'designated sources and destinations (e.g., networks, individuals, and devices) for CUI within systems and between interconnected systems are identified.' },
    { letter: 'd', text: 'authorizations for controlling the flow of CUI are defined.' },
    { letter: 'e', text: 'approved authorizations for controlling the flow of CUI are enforced.' },
  ],
  'AC.L2-3.1.4': [
    { letter: 'a', text: 'the duties of individuals requiring separation to reduce the risk of malevolent activity are defined.' },
    { letter: 'b', text: 'organization-defined duties of individuals requiring separation are separated.' },
    { letter: 'c', text: 'separate accounts for individuals whose duties and accesses must be separated to reduce the risk of malevolent activity or collusion are established' },
  ],
  'AC.L2-3.1.5': [
    { letter: 'a', text: 'privileged accounts are identified.' },
    { letter: 'b', text: 'access to privileged accounts is authorized in accordance with the principle of least privilege.' },
    { letter: 'c', text: 'security functions are identified.' },
    { letter: 'd', text: 'access to security functions is authorized in accordance with the principle of least privilege.' },
  ],
  'AC.L2-3.1.6': [
    { letter: 'a', text: 'nonsecurity functions are identified.' },
    { letter: 'b', text: 'users are required to use non-privileged accounts or roles when accessing nonsecurity functions.' },
  ],
  'AC.L2-3.1.7': [
    { letter: 'a', text: 'privileged functions are defined.' },
    { letter: 'b', text: 'non-privileged users are defined.' },
    { letter: 'c', text: 'non-privileged users are prevented from executing privileged functions.' },
    { letter: 'd', text: 'the execution of privileged functions is captured in audit logs.' },
  ],
  'AC.L2-3.1.8': [
    { letter: 'a', text: 'the means of limiting unsuccessful logon attempts is defined.' },
    { letter: 'b', text: 'the defined means of limiting unsuccessful logon attempts is implemented.' },
  ],
  'AC.L2-3.1.9': [
    { letter: 'a', text: 'privacy and security notices required by CUI-specified rules are identified, consistent, and associated with the specific CUI category' },
    { letter: 'b', text: 'privacy and security notices are displayed.' },
  ],
  'AT.L2-3.2.1': [
    { letter: 'a', text: 'security risks associated with organizational activities involving CUI are identified.' },
    { letter: 'b', text: 'policies, standards, and procedures related to the security of the system are identified.' },
    { letter: 'c', text: 'managers, systems administrators, and users of the system are made aware of the security risks associated with their activities.' },
    { letter: 'd', text: 'managers, systems administrators, and users of the system are made aware of the applicable policies, standards, and procedures related to the security of the system.' },
  ],
  'AT.L2-3.2.2': [
    { letter: 'a', text: 'information security-related duties, roles, and responsibilities are defined.' },
    { letter: 'b', text: 'information security-related duties, roles, and responsibilities are assigned to designated personnel.' },
    { letter: 'c', text: 'personnel are adequately trained to carry out their assigned information security-related duties, roles, and responsibilities.' },
  ],
  'AT.L2-3.2.3': [
    { letter: 'a', text: 'potential indicators associated with insider threats are identified.' },
    { letter: 'b', text: 'security awareness training on recognizing and reporting potential indicators of insider threat is provided to managers and employees.' },
  ],
  'AU.L2-3.3.1': [
    { letter: 'a', text: 'audit logs needed (i.e., event types to be logged) to enable the monitoring, analysis, investigation, and reporting of unlawful or unauthorized system activity are specified.' },
    { letter: 'b', text: 'the content of audit records needed to support monitoring, analysis, investigation, and reporting of unlawful or unauthorized system activity is defined.' },
    { letter: 'c', text: 'audit records are created (generated).' },
    { letter: 'd', text: 'audit records, once created, contain the defined content.' },
    { letter: 'e', text: 'retention requirements for audit records are defined.' },
    { letter: 'f', text: 'audit records are retained as defined.' },
  ],
  'AU.L2-3.3.2': [
    { letter: 'a', text: 'the content of the audit records needed to support the ability to uniquely trace users to their actions is defined.' },
    { letter: 'b', text: 'audit records, once created, contain the defined content.' },
  ],
  'AU.L2-3.3.3': [
    { letter: 'a', text: 'a process for determining when to review logged events is defined.' },
    { letter: 'b', text: 'event types being logged are reviewed in accordance with the defined review process.' },
    { letter: 'c', text: 'event types being logged are updated based on the review.' },
  ],
  'AU.L2-3.3.4': [
    { letter: 'a', text: 'personnel or roles to be alerted in the event of an audit logging process failure are identified.' },
    { letter: 'b', text: 'types of audit logging process failures for which alert will be generated are defined.' },
    { letter: 'c', text: 'identified personnel or roles are alerted in the event of an audit logging process failure.' },
  ],
  'AU.L2-3.3.5': [
    { letter: 'a', text: 'audit record review, analysis, and reporting processes for investigation and response to indications of unlawful, unauthorized, suspicious, or unusual activity are defined.' },
    { letter: 'b', text: 'defined audit record review, analysis, and reporting processes are correlated.' },
  ],
  'AU.L2-3.3.6': [
    { letter: 'a', text: 'an audit record reduction capability that supports on-demand analysis is provided.' },
    { letter: 'b', text: 'a report generation capability that supports on-demand reporting is provided.' },
  ],
  'AU.L2-3.3.7': [
    { letter: 'a', text: 'internal system clocks are used to generate time stamps for audit records.' },
    { letter: 'b', text: 'an authoritative source with which to compare and synchronize internal system clocks is specified.' },
    { letter: 'c', text: 'internal system clocks used to generate time stamps for audit records are compared to and synchronized with the specified authoritative time source.' },
  ],
  'AU.L2-3.3.8': [
    { letter: 'a', text: 'audit information is protected from unauthorized access.' },
    { letter: 'b', text: 'audit information is protected from unauthorized modification.' },
    { letter: 'c', text: 'audit information is protected from unauthorized deletion.' },
    { letter: 'd', text: 'audit logging tools are protected from unauthorized access.' },
    { letter: 'e', text: 'audit logging tools are protected from unauthorized modification.' },
    { letter: 'f', text: 'audit logging tools are protected from unauthorized deletion.' },
  ],
  'AU.L2-3.3.9': [
    { letter: 'a', text: 'a subset of privileged users granted access to manage audit logging functionality is defined.' },
    { letter: 'b', text: 'management of audit logging functionality is limited to the defined subset of privileged users.' },
  ],
  'CA.L2-3.12.1': [
    { letter: 'a', text: 'the frequency of security control assessments is defined.' },
    { letter: 'b', text: 'security controls are assessed with the defined frequency to determine if the controls are effective in their application.' },
  ],
  'CA.L2-3.12.2': [
    { letter: 'a', text: 'deficiencies and vulnerabilities to be addressed by the plan of action are identified.' },
    { letter: 'b', text: 'a plan of action is developed to correct identified deficiencies and reduce or eliminate identified vulnerabilities.' },
    { letter: 'c', text: 'the plan of action is implemented to correct identified deficiencies and reduce or eliminate identified vulnerabilities.' },
  ],
  'CA.L2-3.12.4': [
    { letter: 'a', text: 'a system security plan is developed.' },
    { letter: 'b', text: 'the system boundary is described and documented in the system security plan.' },
    { letter: 'c', text: 'the system environment of operation is described and documented in the system security plan.' },
    { letter: 'd', text: 'the security requirements identified and approved by the designated authority as non-applicable are identified.' },
    { letter: 'e', text: 'the method of security requirement implementation is described and documented in the system security plan.' },
    { letter: 'f', text: 'the relationship with or connection to other systems is described and documented in the system security plan.' },
    { letter: 'g', text: 'the frequency to update the system security plan is defined.' },
    { letter: 'h', text: 'system security plan is updated with the defined frequency.' },
  ],
  'CM.L2-3.4.1': [
    { letter: 'a', text: 'a baseline configuration is established.' },
    { letter: 'b', text: 'the baseline configuration includes hardware, software, firmware, and documentation.' },
    { letter: 'c', text: 'the baseline configuration is maintained (reviewed and updated) throughout the system development life cycle.' },
    { letter: 'd', text: 'a system inventory is established.' },
    { letter: 'e', text: 'the system inventory includes hardware, software, firmware, and documentation.' },
    { letter: 'f', text: 'the inventory is maintained (reviewed and updated) throughout the system development life cycle.' },
  ],
  'CM.L2-3.4.2': [
    { letter: 'a', text: 'security configuration settings for information technology products employed in the system are established and included in the baseline configuration.' },
    { letter: 'b', text: 'security configuration settings for information technology products employed in the system are enforced.' },
  ],
  'CM.L2-3.4.3': [
    { letter: 'a', text: 'changes to the system are tracked.' },
    { letter: 'b', text: 'changes to the system are reviewed.' },
    { letter: 'c', text: 'changes to the system are approved or disapproved.' },
    { letter: 'd', text: 'changes to the system are logged.' },
  ],
  'CM.L2-3.4.5': [
    { letter: 'a', text: 'physical access restrictions associated with changes to the system are defined.' },
    { letter: 'b', text: 'physical access restrictions associated with changes to the system are documented.' },
    { letter: 'c', text: 'physical access restrictions associated with changes to the system are approved.' },
    { letter: 'd', text: 'physical access restrictions associated with changes to the system are enforced.' },
    { letter: 'e', text: 'logical access restrictions associated with changes to the system are defined.' },
    { letter: 'f', text: 'logical access restrictions associated with changes to the system are documented.' },
    { letter: 'g', text: 'logical access restrictions associated with changes to the system are approved.' },
    { letter: 'h', text: 'logical access restrictions associated with changes to the system are enforced.' },
  ],
  'CM.L2-3.4.6': [
    { letter: 'a', text: 'essential system capabilities are defined based on the principle of least functionality.' },
    { letter: 'b', text: 'the system is configured to provide only the defined essential capabilities.' },
  ],
  'CM.L2-3.4.7': [
    { letter: 'a', text: 'essential programs are defined.' },
    { letter: 'b', text: 'the use of nonessential programs is defined.' },
    { letter: 'c', text: 'the use of nonessential programs is restricted, disabled, or prevented as defined.' },
    { letter: 'd', text: 'essential functions are defined.' },
    { letter: 'e', text: 'the use of nonessential functions is defined.' },
    { letter: 'f', text: 'the use of nonessential functions is restricted, disabled, or prevented as defined.' },
    { letter: 'g', text: 'essential ports are defined.' },
    { letter: 'h', text: 'the use of nonessential ports is defined.' },
    { letter: 'i', text: 'the use of nonessential ports is restricted, disabled, or prevented as defined.' },
    { letter: 'j', text: 'essential protocols are defined.' },
    { letter: 'k', text: 'the use of nonessential protocols is defined.' },
    { letter: 'l', text: 'the use of nonessential protocols is restricted, disabled, or prevented as defined.' },
    { letter: 'm', text: 'essential services are defined.' },
    { letter: 'n', text: 'the use of nonessential services is defined.' },
    { letter: 'o', text: 'the use of nonessential services is restricted, disabled, or prevented as defined.' },
  ],
  'CM.L2-3.4.8': [
    { letter: 'a', text: 'a policy specifying whether whitelisting or blacklisting is to be implemented is specified.' },
    { letter: 'b', text: 'the software allowed to execute under whitelisting or denied use under blacklisting is specified.' },
    { letter: 'c', text: 'whitelisting to allow the execution of authorized software or blacklisting to prevent the use of unauthorized software is implemented as specified.' },
  ],
  'CM.L2-3.4.9': [
    { letter: 'a', text: 'a policy for controlling the installation of software by users is established.' },
    { letter: 'b', text: 'installation of software by users is controlled based on the established policy.' },
    { letter: 'c', text: 'installation of software by users is monitored.' },
  ],
  'IA.L2-3.5.1': [
    { letter: 'a', text: 'system users are identified.' },
    { letter: 'b', text: 'processes acting on behalf of users are identified.' },
    { letter: 'c', text: 'devices accessing the system are identified.' },
  ],
  'IA.L2-3.5.10': [
    { letter: 'a', text: 'passwords are cryptographically protected in storage.' },
    { letter: 'b', text: 'passwords are cryptographically protected in transit.' },
  ],
  'IA.L2-3.5.2': [
    { letter: 'a', text: 'the identity of each user is authenticated or verified as a prerequisite to system access.' },
    { letter: 'b', text: 'the identity of each process acting on behalf of a user is authenticated or verified as a prerequisite to system access.' },
    { letter: 'c', text: 'the identity of each device accessing or connecting to the system is authenticated or verified as a prerequisite to system access.' },
  ],
  'IA.L2-3.5.3': [
    { letter: 'a', text: 'privileged accounts are identified.' },
    { letter: 'b', text: 'multifactor authentication is implemented for local access to privileged accounts.' },
    { letter: 'c', text: 'multifactor authentication is implemented for network access to privileged accounts.' },
    { letter: 'd', text: 'multifactor authentication is implemented for network access to non-privileged accounts.' },
  ],
  'IA.L2-3.5.5': [
    { letter: 'a', text: 'a period within which identifiers cannot be reused is defined.' },
    { letter: 'b', text: 'reuse of identifiers is prevented within the defined period.' },
  ],
  'IA.L2-3.5.6': [
    { letter: 'a', text: 'a period of inactivity after which an identifier is disabled is defined.' },
    { letter: 'b', text: 'identifiers are disabled after the defined period of inactivity.' },
  ],
  'IA.L2-3.5.7': [
    { letter: 'a', text: 'password complexity requirements are defined.' },
    { letter: 'b', text: 'password change of character requirements are defined.' },
    { letter: 'c', text: 'minimum password complexity requirements as defined are enforced when new passwords are created.' },
    { letter: 'd', text: 'minimum password change of character requirements as defined are enforced when new passwords are created.' },
  ],
  'IA.L2-3.5.8': [
    { letter: 'a', text: 'the number of generations during which a password cannot be reused is specified.' },
    { letter: 'b', text: 'reuse of passwords is prohibited during the specified number of generations.' },
  ],
  'IR.L2-3.6.1': [
    { letter: 'a', text: 'an operational incident-handling capability is established.' },
    { letter: 'b', text: 'the operational incident-handling capability includes preparation.' },
    { letter: 'c', text: 'the operational incident-handling capability includes detection.' },
    { letter: 'd', text: 'the operational incident-handling capability includes analysis.' },
    { letter: 'e', text: 'the operational incident-handling capability includes containment.' },
    { letter: 'f', text: 'the operational incident-handling capability includes recovery.' },
    { letter: 'g', text: 'the operational incident-handling capability includes user response activities.' },
  ],
  'IR.L2-3.6.2': [
    { letter: 'a', text: 'incidents are tracked.' },
    { letter: 'b', text: 'incidents are documented.' },
    { letter: 'c', text: 'authorities to whom incidents are to be reported are identified.' },
    { letter: 'd', text: 'organizational officials to whom incidents are to be reported are identified.' },
    { letter: 'e', text: 'identified authorities are notified of incidents.' },
    { letter: 'f', text: 'identified organizational officials are notified of incidents.' },
  ],
  'MA.L2-3.7.2': [
    { letter: 'a', text: 'tools used to conduct system maintenance are controlled.' },
    { letter: 'b', text: 'techniques used to conduct system maintenance are controlled.' },
    { letter: 'c', text: 'mechanisms used to conduct system maintenance are controlled.' },
    { letter: 'd', text: 'personnel used to conduct system maintenance are controlled.' },
  ],
  'MA.L2-3.7.5': [
    { letter: 'a', text: 'multifactor authentication is required to establish nonlocal maintenance sessions via external network connections.' },
    { letter: 'b', text: 'nonlocal maintenance sessions established via external network connections are terminated when nonlocal maintenance is complete.' },
  ],
  'MP.L2-3.8.1': [
    { letter: 'a', text: 'paper media containing CUI is physically controlled.' },
    { letter: 'b', text: 'digital media containing CUI is physically controlled.' },
    { letter: 'c', text: 'paper media containing CUI is securely stored.' },
    { letter: 'd', text: 'digital media containing CUI is securely stored.' },
  ],
  'MP.L2-3.8.3': [
    { letter: 'a', text: 'system media containing CUI is sanitized or destroyed before disposal.' },
    { letter: 'b', text: 'system media containing CUI is sanitized before it is released for reuse.' },
  ],
  'MP.L2-3.8.4': [
    { letter: 'a', text: 'media containing CUI is marked with applicable CUI markings.' },
    { letter: 'b', text: 'media containing CUI is marked with distribution limitations.' },
  ],
  'MP.L2-3.8.5': [
    { letter: 'a', text: 'access to media containing CUI is controlled.' },
    { letter: 'b', text: 'accountability for media containing CUI is maintained during transport outside of controlled areas.' },
  ],
  'PE.L2-3.10.1': [
    { letter: 'a', text: 'authorized individuals allowed physical access are identified.' },
    { letter: 'b', text: 'physical access to organizational systems is limited to authorized individuals.' },
    { letter: 'c', text: 'physical access to equipment is limited to authorized individuals.' },
    { letter: 'd', text: 'physical access to operating environments is limited to authorized individuals.' },
  ],
  'PE.L2-3.10.2': [
    { letter: 'a', text: 'the physical facility where that system resides is protected.' },
    { letter: 'b', text: 'the support infrastructure for that system is protected.' },
    { letter: 'c', text: 'the physical facility where that system resides is monitored.' },
    { letter: 'd', text: 'the support infrastructure for that system is monitored.' },
  ],
  'PE.L2-3.10.3': [
    { letter: 'a', text: 'visitors are escorted.' },
    { letter: 'b', text: 'visitor activity is monitored.' },
  ],
  'PE.L2-3.10.5': [
    { letter: 'a', text: 'physical access devices are identified.' },
    { letter: 'b', text: 'physical access devices are controlled.' },
    { letter: 'c', text: 'physical access devices are managed.' },
  ],
  'PE.L2-3.10.6': [
    { letter: 'a', text: 'safeguarding measures for CUI are defined for alternate work sites.' },
    { letter: 'b', text: 'safeguarding measures for CUI are enforced for alternate work sites.' },
  ],
  'PS.L2-3.9.2': [
    { letter: 'a', text: 'a policy and/or process for terminating system access authorization and any credentials coincident with personnel actions is established.' },
    { letter: 'b', text: 'system access and credentials are terminated consistent with personnel actions such as termination or transfer.' },
    { letter: 'c', text: 'the system is protected during and after personnel transfer actions.' },
  ],
  'RA.L2-3.11.1': [
    { letter: 'a', text: 'the frequency to assess risk to organizational operations, organizational assets, and individuals is defined.' },
    { letter: 'b', text: 'risk to organizational operations, organizational assets, and individuals resulting from the operation of an organizational system that processes, stores, or transmits CUI is assessed with the defined frequency.' },
  ],
  'RA.L2-3.11.2': [
    { letter: 'a', text: 'the frequency to scan for vulnerabilities in an organizational system and its applications that process, store, or transmit CUI is defined.' },
    { letter: 'b', text: 'vulnerability scans are performed in an organizational system that processes, stores, or transmits CUI with the defined frequency.' },
    { letter: 'c', text: 'vulnerability scans are performed in an application that contains CUI with the defined frequency.' },
    { letter: 'd', text: 'vulnerability scans are performed in an organizational system that processes, stores, or transmits CUI when new vulnerabilities are identified.' },
    { letter: 'e', text: 'vulnerability scans are performed in an application that contains CUI when new vulnerabilities are identified.' },
  ],
  'RA.L2-3.11.3': [
    { letter: 'a', text: 'vulnerabilities are identified.' },
    { letter: 'b', text: 'vulnerabilities are remediated in accordance with risk assessments.' },
  ],
  'SC.L2-3.13.1': [
    { letter: 'a', text: 'the external system boundary is defined.' },
    { letter: 'b', text: 'key internal system boundaries are defined.' },
    { letter: 'c', text: 'communications are monitored at the external system boundary.' },
    { letter: 'd', text: 'communications are monitored at key internal boundaries.' },
    { letter: 'e', text: 'communications are controlled at the external system boundary.' },
    { letter: 'f', text: 'communications are controlled at key internal boundaries.' },
    { letter: 'g', text: 'communications are protected at the external system boundary.' },
    { letter: 'h', text: 'communications are protected at key internal boundaries.' },
  ],
  'SC.L2-3.13.10': [
    { letter: 'a', text: 'cryptographic keys are established whenever cryptography is employed.' },
    { letter: 'b', text: 'cryptographic keys are managed whenever cryptography is employed.' },
  ],
  'SC.L2-3.13.12': [
    { letter: 'a', text: 'collaborative computing devices are identified.' },
    { letter: 'b', text: 'collaborative computing devices provide indication to users of devices in use.' },
    { letter: 'c', text: 'remote activation of collaborative computing devices is prohibited.' },
  ],
  'SC.L2-3.13.13': [
    { letter: 'a', text: 'use of mobile code is controlled.' },
    { letter: 'b', text: 'use of mobile code is monitored.' },
  ],
  'SC.L2-3.13.14': [
    { letter: 'a', text: 'use of Voice over Internet Protocol (VoIP) technologies is controlled.' },
    { letter: 'b', text: 'use of Voice over Internet Protocol (VoIP) technologies is monitored.' },
  ],
  'SC.L2-3.13.2': [
    { letter: 'a', text: 'architectural designs that promote effective information security are identified.' },
    { letter: 'b', text: 'software development techniques that promote effective information security are identified.' },
    { letter: 'c', text: 'systems engineering principles that promote effective information security are identified.' },
    { letter: 'd', text: 'identified architectural designs that promote effective information security are employed.' },
    { letter: 'e', text: 'identified software development techniques that promote effective information security are employed.' },
    { letter: 'f', text: 'identified systems engineering principles that promote effective information security are employed.' },
  ],
  'SC.L2-3.13.3': [
    { letter: 'a', text: 'user functionality is identified.' },
    { letter: 'b', text: 'system management functionality is identified.' },
    { letter: 'c', text: 'user functionality is separated from system management functionality.' },
  ],
  'SC.L2-3.13.5': [
    { letter: 'a', text: 'publicly accessible system components are identified.' },
    { letter: 'b', text: 'subnetworks for publicly accessible system components are physically or logically separated from internal networks.' },
  ],
  'SC.L2-3.13.6': [
    { letter: 'a', text: 'network communications traffic is denied by default.' },
    { letter: 'b', text: 'network communications traffic is allowed by exception.' },
  ],
  'SC.L2-3.13.8': [
    { letter: 'a', text: 'cryptographic mechanisms intended to prevent unauthorized disclosure of CUI are identified.' },
    { letter: 'b', text: 'alternative physical safeguards intended to prevent unauthorized disclosure of CUI are identified.' },
    { letter: 'c', text: 'either cryptographic mechanisms or alternative physical safeguards are implemented to prevent unauthorized disclosure of CUI during transmission.' },
  ],
  'SC.L2-3.13.9': [
    { letter: 'a', text: 'a period of inactivity to terminate network connections associated with communications sessions is defined.' },
    { letter: 'b', text: 'network connections associated with communications sessions are terminated at the end of the sessions.' },
    { letter: 'c', text: 'network connections associated with communications sessions are terminated after the defined period of inactivity.' },
  ],
  'SI.L2-3.14.1': [
    { letter: 'a', text: 'the time within which to identify system flaws is specified.' },
    { letter: 'b', text: 'system flaws are identified within the specified time frame.' },
    { letter: 'c', text: 'the time within which to report system flaws is specified.' },
    { letter: 'd', text: 'system flaws are reported within the specified time frame.' },
    { letter: 'e', text: 'the time within which to correct system flaws is specified.' },
    { letter: 'f', text: 'system flaws are corrected within the specified time frame.' },
  ],
  'SI.L2-3.14.2': [
    { letter: 'a', text: 'designated locations for malicious code protection are identified.' },
    { letter: 'b', text: 'protection from malicious code at designated locations is provided.' },
  ],
  'SI.L2-3.14.3': [
    { letter: 'a', text: 'response actions to system security alerts and advisories are identified.' },
    { letter: 'b', text: 'system security alerts and advisories are monitored.' },
    { letter: 'c', text: 'actions in response to system security alerts and advisories are taken.' },
  ],
  'SI.L2-3.14.5': [
    { letter: 'a', text: 'the frequency for malicious code scans is defined.' },
    { letter: 'b', text: 'malicious code scans are performed with the defined frequency.' },
    { letter: 'c', text: 'real-time malicious code scans of files from external sources as files are downloaded, opened, or executed are performed.' },
  ],
  'SI.L2-3.14.6': [
    { letter: 'a', text: 'the system is monitored to detect attacks and indicators of potential attacks.' },
    { letter: 'b', text: 'inbound communications traffic is monitored to detect attacks and indicators of potential attacks.' },
    { letter: 'c', text: 'outbound communications traffic is monitored to detect attacks and indicators of potential attacks.' },
  ],
  'SI.L2-3.14.7': [
    { letter: 'a', text: 'authorized use of the system is defined.' },
    { letter: 'b', text: 'unauthorized use of the system is identified.' },
  ],
}
