export type PracticeEntry = { id: string; title: string }
export type DomainEntry = { abbr: string; name: string; practices: PracticeEntry[] }

export const PRACTICE_DOMAINS: DomainEntry[] = [
  {
    abbr: 'AC', name: 'Access Control',
    practices: [
      { id: 'AC.L2-3.1.1',  title: 'Limit System Access to Authorized Users' },
      { id: 'AC.L2-3.1.2',  title: 'Limit System Access to Types of Transactions and Functions' },
      { id: 'AC.L2-3.1.3',  title: 'Control CUI Flow' },
      { id: 'AC.L2-3.1.4',  title: 'Separate Duties of Individuals' },
      { id: 'AC.L2-3.1.5',  title: 'Employ Least Privilege' },
      { id: 'AC.L2-3.1.6',  title: 'Use Non-Privileged Accounts or Roles' },
      { id: 'AC.L2-3.1.7',  title: 'Prevent Non-Privileged Users from Executing Privileged Functions' },
      { id: 'AC.L2-3.1.8',  title: 'Limit Unsuccessful Logon Attempts' },
      { id: 'AC.L2-3.1.9',  title: 'Provide Privacy and Security Notices' },
      { id: 'AC.L2-3.1.10', title: 'Use Session Lock' },
      { id: 'AC.L2-3.1.11', title: 'Terminate Sessions' },
      { id: 'AC.L2-3.1.12', title: 'Monitor and Control Remote Access Sessions' },
      { id: 'AC.L2-3.1.13', title: 'Employ Cryptographic Mechanisms to Protect CUI During Transmission' },
      { id: 'AC.L2-3.1.14', title: 'Route Remote Access via Managed Access Control Points' },
      { id: 'AC.L2-3.1.15', title: 'Authorize Remote Execution of Privileged Commands' },
      { id: 'AC.L2-3.1.16', title: 'Authorize Wireless Access' },
      { id: 'AC.L2-3.1.17', title: 'Protect Wireless Access Using Authentication and Encryption' },
      { id: 'AC.L2-3.1.18', title: 'Control Connection of Mobile Devices' },
      { id: 'AC.L2-3.1.19', title: 'Encrypt CUI on Mobile Devices' },
      { id: 'AC.L2-3.1.20', title: 'Verify and Control All Connections to External Systems' },
      { id: 'AC.L2-3.1.21', title: 'Limit Use of Portable Storage Devices on External Systems' },
      { id: 'AC.L2-3.1.22', title: 'Control CUI Posted or Processed on Publicly Accessible Systems' },
    ],
  },
  {
    abbr: 'AT', name: 'Awareness and Training',
    practices: [
      { id: 'AT.L2-3.2.1', title: 'Ensure Personnel Awareness' },
      { id: 'AT.L2-3.2.2', title: 'Ensure Personnel Training' },
      { id: 'AT.L2-3.2.3', title: 'Provide Security Awareness Training on Recognizing and Reporting Threats' },
    ],
  },
  {
    abbr: 'AU', name: 'Audit and Accountability',
    practices: [
      { id: 'AU.L2-3.3.1', title: 'Create and Retain System Audit Logs' },
      { id: 'AU.L2-3.3.2', title: 'Ensure User Accountability via Audit Logs' },
      { id: 'AU.L2-3.3.3', title: 'Review and Update Logged Events' },
      { id: 'AU.L2-3.3.4', title: 'Alert in the Event of Audit Process Failure' },
      { id: 'AU.L2-3.3.5', title: 'Correlate Audit Record Review, Analysis, and Reporting' },
      { id: 'AU.L2-3.3.6', title: 'Provide Audit Record Reduction and Report Generation' },
      { id: 'AU.L2-3.3.7', title: 'Provide System Capability Supporting Audit Reduction' },
      { id: 'AU.L2-3.3.8', title: 'Protect Audit Information and Tools' },
      { id: 'AU.L2-3.3.9', title: 'Limit Management of Audit Logging to Subset of Privileged Users' },
    ],
  },
  {
    abbr: 'CA', name: 'Security Assessment',
    practices: [
      { id: 'CA.L2-3.12.1', title: 'Periodically Assess Security Controls' },
      { id: 'CA.L2-3.12.2', title: 'Develop and Implement Plans of Action' },
      { id: 'CA.L2-3.12.3', title: 'Monitor Security Controls on an Ongoing Basis' },
      { id: 'CA.L2-3.12.4', title: 'Develop, Document, and Periodically Update System Security Plans' },
    ],
  },
  {
    abbr: 'CM', name: 'Configuration Management',
    practices: [
      { id: 'CM.L2-3.4.1', title: 'Establish Configuration Baselines' },
      { id: 'CM.L2-3.4.2', title: 'Establish and Enforce Security Configuration Settings' },
      { id: 'CM.L2-3.4.3', title: 'Track, Review, Approve, and Log Changes to Systems' },
      { id: 'CM.L2-3.4.4', title: 'Analyze Security Impact of Changes Prior to Implementation' },
      { id: 'CM.L2-3.4.5', title: 'Define, Document, Approve, and Enforce Physical and Logical Access Restrictions' },
      { id: 'CM.L2-3.4.6', title: 'Employ Principle of Least Functionality' },
      { id: 'CM.L2-3.4.7', title: 'Restrict, Disable, or Prevent the Use of Nonessential Programs' },
      { id: 'CM.L2-3.4.8', title: 'Apply Deny-by-Exception Policy to Prevent Use of Unauthorized Software' },
      { id: 'CM.L2-3.4.9', title: 'Control and Monitor User-Installed Software' },
    ],
  },
  {
    abbr: 'IA', name: 'Identification and Authentication',
    practices: [
      { id: 'IA.L2-3.5.1',  title: 'Identify System Users, Processes, and Devices' },
      { id: 'IA.L2-3.5.2',  title: 'Authenticate Users, Processes, and Devices' },
      { id: 'IA.L2-3.5.3',  title: 'Use Multifactor Authentication for Local and Network Access' },
      { id: 'IA.L2-3.5.4',  title: 'Employ Replay-Resistant Authentication Mechanisms' },
      { id: 'IA.L2-3.5.5',  title: 'Employ Identifier Management' },
      { id: 'IA.L2-3.5.6',  title: 'Employ Authentication Management' },
      { id: 'IA.L2-3.5.7',  title: 'Enforce Minimum Password Complexity and Change Requirements' },
      { id: 'IA.L2-3.5.8',  title: 'Prohibit Password Reuse' },
      { id: 'IA.L2-3.5.9',  title: 'Allow Temporary Password Use with Immediate Change Requirement' },
      { id: 'IA.L2-3.5.10', title: 'Store and Transmit Only Cryptographically Protected Passwords' },
      { id: 'IA.L2-3.5.11', title: 'Obscure Feedback of Authentication Information' },
    ],
  },
  {
    abbr: 'IR', name: 'Incident Response',
    practices: [
      { id: 'IR.L2-3.6.1', title: 'Establish an Operational Incident-Handling Capability' },
      { id: 'IR.L2-3.6.2', title: 'Track, Document, and Report Incidents' },
      { id: 'IR.L2-3.6.3', title: 'Test Incident Response Capability' },
    ],
  },
  {
    abbr: 'MA', name: 'Maintenance',
    practices: [
      { id: 'MA.L2-3.7.1', title: 'Perform Maintenance on Organizational Systems' },
      { id: 'MA.L2-3.7.2', title: 'Provide Controls on the Tools, Techniques, Mechanisms, and Personnel for Maintenance' },
      { id: 'MA.L2-3.7.3', title: 'Ensure Equipment Removed for Maintenance is Sanitized' },
      { id: 'MA.L2-3.7.4', title: 'Check Media Containing Diagnostic and Test Programs for Malicious Code' },
      { id: 'MA.L2-3.7.5', title: 'Require MFA for Remote Maintenance Sessions' },
      { id: 'MA.L2-3.7.6', title: 'Supervise Maintenance Activities of Personnel Without Required Access Authorization' },
    ],
  },
  {
    abbr: 'MP', name: 'Media Protection',
    practices: [
      { id: 'MP.L2-3.8.1', title: 'Protect System Media Containing CUI' },
      { id: 'MP.L2-3.8.2', title: 'Limit Access to CUI on System Media' },
      { id: 'MP.L2-3.8.3', title: 'Sanitize or Destroy System Media Before Disposal or Reuse' },
      { id: 'MP.L2-3.8.4', title: 'Mark Media with Necessary CUI Markings and Distribution Limitations' },
      { id: 'MP.L2-3.8.5', title: 'Control Access to Media Containing CUI' },
      { id: 'MP.L2-3.8.6', title: 'Implement Cryptographic Mechanisms to Protect CUI During Transport' },
      { id: 'MP.L2-3.8.7', title: 'Control the Use of Removable Media on System Components' },
      { id: 'MP.L2-3.8.8', title: 'Prohibit the Use of Portable Storage Without Identifiable Owner' },
      { id: 'MP.L2-3.8.9', title: 'Protect Backups of CUI' },
    ],
  },
  {
    abbr: 'PE', name: 'Physical Protection',
    practices: [
      { id: 'PE.L2-3.10.1', title: 'Limit Physical Access to Organizational Systems' },
      { id: 'PE.L2-3.10.2', title: 'Protect and Monitor the Physical Facility and Support Infrastructure' },
      { id: 'PE.L2-3.10.3', title: 'Escort Visitors and Monitor Visitor Activity' },
      { id: 'PE.L2-3.10.4', title: 'Maintain Audit Logs of Physical Access' },
      { id: 'PE.L2-3.10.5', title: 'Control and Manage Physical Access Devices' },
      { id: 'PE.L2-3.10.6', title: 'Enforce Safeguarding Measures for CUI at Alternate Work Sites' },
    ],
  },
  {
    abbr: 'PS', name: 'Personnel Security',
    practices: [
      { id: 'PS.L2-3.9.1', title: 'Screen Individuals Prior to Authorizing Access to Systems' },
      { id: 'PS.L2-3.9.2', title: 'Ensure CUI is Protected During and After Personnel Actions' },
    ],
  },
  {
    abbr: 'RA', name: 'Risk Assessment',
    practices: [
      { id: 'RA.L2-3.11.1', title: 'Periodically Assess Risk to Organizational Operations, Assets, and Individuals' },
      { id: 'RA.L2-3.11.2', title: 'Scan for Vulnerabilities in Organizational Systems and Applications Periodically' },
      { id: 'RA.L2-3.11.3', title: 'Remediate Vulnerabilities in Accordance with Risk Assessments' },
    ],
  },
  {
    abbr: 'SC', name: 'System and Communications Protection',
    practices: [
      { id: 'SC.L2-3.13.1',  title: 'Monitor, Control, and Protect Communications at External Boundaries' },
      { id: 'SC.L2-3.13.2',  title: 'Employ Architectural Designs, Software Development Techniques, and Systems Engineering Principles' },
      { id: 'SC.L2-3.13.3',  title: 'Separate User Functionality from System Management Functionality' },
      { id: 'SC.L2-3.13.4',  title: 'Prevent Unauthorized and Unintended Information Transfer' },
      { id: 'SC.L2-3.13.5',  title: 'Implement Subnetworks for Publicly Accessible System Components' },
      { id: 'SC.L2-3.13.6',  title: 'Deny Network Communications Traffic by Default' },
      { id: 'SC.L2-3.13.7',  title: 'Prevent Remote Devices from Simultaneously Using Non-Remote Connections' },
      { id: 'SC.L2-3.13.8',  title: 'Implement Cryptographic Mechanisms to Prevent Unauthorized Disclosure of CUI' },
      { id: 'SC.L2-3.13.9',  title: 'Terminate Network Connections After Defined Period of Inactivity' },
      { id: 'SC.L2-3.13.10', title: 'Establish and Manage Cryptographic Keys' },
      { id: 'SC.L2-3.13.11', title: 'Employ FIPS-Validated Cryptography When Used to Protect CUI' },
      { id: 'SC.L2-3.13.12', title: 'Prohibit Remote Activation of Collaborative Computing Devices' },
      { id: 'SC.L2-3.13.13', title: 'Control and Monitor the Use of Mobile Code' },
      { id: 'SC.L2-3.13.14', title: 'Control and Monitor the Use of VoIP Technologies' },
      { id: 'SC.L2-3.13.15', title: 'Protect the Authenticity of Communications Sessions' },
      { id: 'SC.L2-3.13.16', title: 'Protect CUI at Rest' },
    ],
  },
  {
    abbr: 'SI', name: 'System and Information Integrity',
    practices: [
      { id: 'SI.L2-3.14.1', title: 'Identify, Report, and Correct System Flaws' },
      { id: 'SI.L2-3.14.2', title: 'Provide Protection from Malicious Code at Appropriate Locations' },
      { id: 'SI.L2-3.14.3', title: 'Monitor System Security Alerts and Advisories' },
      { id: 'SI.L2-3.14.4', title: 'Update Malicious Code Protection Mechanisms' },
      { id: 'SI.L2-3.14.5', title: 'Perform Periodic Scans of Systems and Real-Time Scans of Files from External Sources' },
      { id: 'SI.L2-3.14.6', title: 'Monitor Systems to Detect Attacks and Indicators of Potential Attacks' },
      { id: 'SI.L2-3.14.7', title: 'Identify Unauthorized Use of Systems' },
    ],
  },
  {
    abbr: 'ITAR', name: 'ITAR Compliance',
    practices: [
      { id: 'ITAR-P-001',  title: 'Screen Employees for ITAR-Controlled Data Access' },
      { id: 'ITAR-P-002',  title: 'Maintain Records of ITAR Data Access' },
      { id: 'ITAR-P-003',  title: 'Conduct Annual ITAR Awareness Training' },
      { id: 'ITAR-P-004',  title: 'Implement Foreign National Access Restrictions' },
      { id: 'ITAR-P-005',  title: 'Document Employee ITAR Agreements' },
      { id: 'ITAR-DR-001', title: 'Ensure ITAR Data Remains in U.S. Jurisdiction' },
      { id: 'ITAR-DR-002', title: 'Restrict Cloud Storage to U.S.-Only Services' },
      { id: 'ITAR-DR-003', title: 'Document ITAR Data Flows' },
      { id: 'ITAR-DR-004', title: 'Prevent Unauthorized Transfer to Foreign Entities' },
      { id: 'ITAR-AB-001', title: 'Implement Logical Access Controls for ITAR Systems' },
      { id: 'ITAR-AB-002', title: 'Segregate ITAR Data from Non-ITAR Systems' },
      { id: 'ITAR-AB-003', title: 'Enforce Need-to-Know for ITAR Data' },
      { id: 'ITAR-AB-004', title: 'Monitor and Log ITAR System Access' },
      { id: 'ITAR-D-001',  title: 'Document ITAR Disclosures and Export Authorizations' },
      { id: 'ITAR-D-002',  title: 'Obtain Required Licenses Before External Sharing' },
      { id: 'ITAR-D-003',  title: 'Maintain ITAR Export Activity Records for 5 Years' },
      { id: 'ITAR-D-004',  title: 'Report Unauthorized Disclosures to DDTC' },
      { id: 'ITAR-T-001',  title: 'Conduct Initial ITAR Compliance Training' },
      { id: 'ITAR-T-002',  title: 'Provide Role-Specific Training for Export Control Officers' },
      { id: 'ITAR-T-003',  title: 'Track and Verify ITAR Training Completion' },
    ],
  },
]
