import type { NextRequest} from 'next/server';
import { NextResponse } from 'next/server'
import bcrypt from 'bcryptjs'
import { getAuthSession } from '@/lib/get-session'
import { requireRole } from '@/lib/auth'
import { checkCsrf } from '@/lib/api-csrf'
import { audit, getClientIp } from '@/lib/audit'
import { parseFactoryReset, validationError } from '@/lib/validation'
import { validatePayload, restoreFromPayload } from '@/lib/restore'
import sql from '@/lib/db'
import { readFile } from 'node:fs/promises'
import path from 'node:path'

export const dynamic = 'force-dynamic'

/**
 * POST /api/admin/factory-reset
 *
 * Restores the database to the golden baseline state.
 * Reads from scripts/data/baseline.json (generated by generate-baseline.ts).
 *
 * This is a destructive operation: all current data is replaced.
 * Requires admin role + CSRF token.
 */
export async function POST(req: NextRequest) {
  const csrfError = checkCsrf(req)
  if (csrfError) return csrfError

  const session = await getAuthSession()
  const authError = requireRole(session, 'admin')
  if (authError) return authError

  // Parse confirmation password from request body
  let rawBody: unknown
  try {
    rawBody = await req.json()
  } catch {
    return NextResponse.json({ error: 'Request body with confirm_password required' }, { status: 400 })
  }

  const confirmParsed = parseFactoryReset(rawBody)
  if (!confirmParsed.success) return validationError(confirmParsed.error)

  const adminEmail = session!.user.email!
  const [adminUser] = await sql<{ password_hash: string }[]>`
    SELECT password_hash FROM users WHERE email = ${adminEmail}
  `
  if (!adminUser) return NextResponse.json({ error: 'Admin user not found' }, { status: 403 })

  const passwordValid = await bcrypt.compare(confirmParsed.data.confirm_password, adminUser.password_hash)
  if (!passwordValid) {
    await audit({
      action: 'factory.reset.denied',
      actor: adminEmail,
      ip: getClientIp(req.headers),
      details: 'Wrong confirmation password',
    })
    return NextResponse.json({ error: 'Incorrect password' }, { status: 403 })
  }

  // Load baseline file
  const baselinePath = path.resolve(process.cwd(), 'scripts/data/baseline.json')
  let raw: string
  try {
    raw = await readFile(baselinePath, 'utf8')
  } catch {
    return NextResponse.json(
      {
        error: 'Baseline file not found. Run: npx tsx scripts/generate-baseline.ts',
      },
      { status: 404 }
    )
  }

  let parsed: unknown
  try {
    parsed = JSON.parse(raw)
  } catch {
    return NextResponse.json({ error: 'Baseline file is not valid JSON.' }, { status: 500 })
  }

  try {
    validatePayload(parsed)
  } catch (err) {
    return NextResponse.json({ error: (err as Error).message }, { status: 500 })
  }

  try {
    await restoreFromPayload(parsed)
    // Factory reset clears the audit log — start clean
    await sql`TRUNCATE security_events RESTART IDENTITY`
  } catch (err) {
    console.error('Factory reset failed:', err)
    return NextResponse.json(
      { error: 'Factory reset failed. The database may not have been modified.' },
      { status: 500 }
    )
  }

  await audit({
    action: 'factory.reset',
    actor: session!.user.email ?? 'admin',
    ip: getClientIp(req.headers),
    details: 'Factory reset to baseline',
  })

  return NextResponse.json({ ok: true, message: 'Factory reset complete. All data restored to baseline.' })
}

/**
 * GET /api/admin/factory-reset
 *
 * Returns metadata about the baseline (when it was generated, whether it exists).
 */
export async function GET() {
  const session = await getAuthSession()
  const authError = requireRole(session, 'admin')
  if (authError) return authError

  const baselinePath = path.resolve(process.cwd(), 'scripts/data/baseline.json')
  try {
    const raw = await readFile(baselinePath, 'utf8')
    const parsed = JSON.parse(raw)
    return NextResponse.json({
      available: true,
      generated_at: parsed._generated_at ?? null,
      users: parsed.users?.length ?? 0,
      domains: parsed.domains?.length ?? 0,
      practices: parsed.practices?.length ?? 0,
    })
  } catch {
    return NextResponse.json({ available: false })
  }
}
