#!/bin/sh
# ─────────────────────────────────────────────────────────────────
# CMMC Dashboard — Secrets Setup Script
# Generates secure random secrets for Docker Compose secrets
# Run once before first `docker compose up`
# ─────────────────────────────────────────────────────────────────
set -eu

SECRETS_DIR="./secrets"

echo "CMMC Dashboard — Secrets Setup"
echo "=============================="
echo ""

# Create secrets directory
mkdir -p "${SECRETS_DIR}"

# Generate PostgreSQL password
PG_FILE="${SECRETS_DIR}/postgres_password.txt"
if [ -f "${PG_FILE}" ]; then
  echo "[SKIP] ${PG_FILE} already exists. Delete it to regenerate."
else
  openssl rand -base64 24 | tr -d '\n' > "${PG_FILE}"
  chmod 600 "${PG_FILE}"
  echo "[OK]   Generated PostgreSQL password → ${PG_FILE}"
fi

# Generate NextAuth secret
NA_FILE="${SECRETS_DIR}/nextauth_secret.txt"
if [ -f "${NA_FILE}" ]; then
  echo "[SKIP] ${NA_FILE} already exists. Delete it to regenerate."
else
  openssl rand -base64 32 | tr -d '\n' > "${NA_FILE}"
  chmod 600 "${NA_FILE}"
  echo "[OK]   Generated NextAuth secret → ${NA_FILE}"
fi

# Set restrictive permissions on the directory
chmod 700 "${SECRETS_DIR}"

echo ""
echo "Secrets are stored in ${SECRETS_DIR}/"
echo "These files are mounted as Docker secrets at /run/secrets/ in each container."
echo ""
echo "IMPORTANT: The secrets/ directory is in .gitignore."
echo "           Never commit these files to version control."
echo ""

# Also create/update .env with the POSTGRES_PASSWORD for docker-compose variable substitution
# (docker-compose needs this for the DATABASE_URL string in the app service)
ENV_FILE=".env"
PG_PASS=$(cat "${PG_FILE}")
NA_PASS=$(cat "${NA_FILE}")

if [ -f "${ENV_FILE}" ]; then
  if grep -q "^POSTGRES_PASSWORD=" "${ENV_FILE}"; then
    echo "[INFO] .env already has POSTGRES_PASSWORD — not overwriting."
  else
    echo "" >> "${ENV_FILE}"
    echo "POSTGRES_PASSWORD=${PG_PASS}" >> "${ENV_FILE}"
    echo "[OK]   Added POSTGRES_PASSWORD to .env"
  fi
  # NEXTAUTH_SECRET is needed by Next.js dev server (auto-loads .env).
  # Production uses docker-entrypoint.sh to read the secret file instead.
  if grep -q "^NEXTAUTH_SECRET=" "${ENV_FILE}"; then
    echo "[INFO] .env already has NEXTAUTH_SECRET — not overwriting."
  else
    echo "NEXTAUTH_SECRET=${NA_PASS}" >> "${ENV_FILE}"
    echo "[OK]   Added NEXTAUTH_SECRET to .env"
  fi
else
  cat > "${ENV_FILE}" <<EOL
# Generated by setup-secrets.sh — DO NOT COMMIT
# The actual secrets live in ./secrets/ as Docker secret files
# This .env is only needed for docker-compose variable substitution
# Note: NEXTAUTH_SECRET here is for dev only — production uses docker-entrypoint.sh

POSTGRES_PASSWORD=${PG_PASS}
NEXTAUTH_SECRET=${NA_PASS}
NEXTAUTH_URL=http://localhost
ORG_NAME=My Organization
EOL
  echo "[OK]   Created .env file"
fi

echo ""
echo "Setup complete. You can now run:"
echo "  docker compose up -d --build"
